version: "3.9"
services:
  dremio:
    container_name: dremio
    image: dremio/dremio-oss:latest
    platform: linux/x86_64
    ports:
    - 9047:9047
    - 31010:31010
    - 32010:32010

  nessie:
      container_name: nessie
      image: projectnessie/nessie
      ports:
        - 19120:19120

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  init-minio:
    container_name: minio-init
    image: minio/mc
    entrypoint: >
      /bin/sh -c "mc config host add minio http://minio:9000 minio minio123; mc mb minio/lake"
    depends_on:
      - minio
